# Site settings
title: The Remote Lab Blog
baseurl: "/blog"
url: "http://theremotelab.io"
twitter: TheRemoteLab
github:  TheRemoteLab
permalink: /:title/
analyticsEnabled: true

# Build settings
markdown: redcarpet
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "disable_indented_code_blocks", "autolink", "strikethrough", "highlight", "superscript", "tables", "footnotes", "with_toc_data"]
highlighter: pygments

collections:
  authors:
  projects:

defaults:
  -
    scope:
      path: ""      # empty string for all files
      type: posts   # limit to posts
    values:
      is_post: true 

gems:
  - jemoji
